# 淬炼成本
Cost:
  Money: 100
  MaterialAmount: 1

#声音提示，填写#视为禁用
Sound:
  # 装备升级成功
  success: 'ENTITY_ARMOR_STAND_BREAK'
  # 装备掉级
  downgrade: 'ITEM_BOTTLE_FILL'

Type:
  #武器
  Arms:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    # 包含的类型
    types:
      - IRON_SWORD
      - NETHERITE_AXE
      - NETHERITE_SWORD
      - IRON_AXE
      - DIAMOND_AXE
      - DIAMOND_SWORD
  #防具
  Armor:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    # 包含的类型
    types:
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_LEGGINGS
      - DIAMOND_BOOTS
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_LEGGINGS
      - NETHERITE_BOOTS
      - ELYTRA
      - SHIELD
  # 自定义
  wode:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    types:
      - BOW
      - CROSSBOW
      - TRIDENT

  # 可以按照如上的自定义格式继续自定义

ItemName:
  DIAMOND_HELMET: '钻石头盔'
  DIAMOND_CHESTPLATE: '钻石胸甲'
  DIAMOND_LEGGINGS: '钻石护腿'
  DIAMOND_BOOTS: '钻石靴子'
  NETHERITE_HELMET: '下界合金头盔'
  NETHERITE_CHESTPLATE: '下界合金胸甲'
  NETHERITE_LEGGINGS: '下界合金护腿'
  NETHERITE_BOOTS: '下界合金靴'
  NETHERITE_AXE: '下界合金斧'
  NETHERITE_SWORD: '下界合金剑'
  IRON_AXE: '铁斧'
  DIAMOND_AXE: '钻石斧'
  DIAMOND_SWORD: '钻石剑'
  BOW: '弓箭'
  ELYTRA: '鞘翅'
  TRIDENT: '三叉戟'
  CROSSBOW: '弩箭'
  SHIELD: '盾牌'

bottomLores:
  - "材质"
  - "皮肤"

# 公告
BroadCast:
  # 是否启用
  enable: true
  # 公告内容
  messages:
    - "<green>恭喜 <yellow><player> <green>将 <item> <green>强化到了 <red><b>+<level> <green>级."
  # 当升级后的等级大于等于该等级，才发布公告
  allowLevel: 10

# 相关物品
Article:
  # 淬炼道具
  temperingTools:
    # 物品名
    displayName: "<aqua><b>一级强化石"
    # 物品类型
    materialType: "DIAMOND"
    # 物品描述
    lores:
      - "<green>这是一颗强化石"
      - "<gray><i>由天地灵气孕育而成..."
    # 物品附魔效果，但是不会有任何属性显示。
    glow: true
    # 允许原版淬炼，无视上述的设定
    setNormal: true
