#插件指令前缀
Prefix: '&7[&d淬炼&7] '

#声音提示，填写#视为禁用
Sound:
  # 装备掉级
  downgrade: 'ITEM_BOTTLE_FILL'
  # 装备无变化
  defeat: 'ENTITY_ARMOR_STAND_BREAK'

#信息提示
Messages:
  # 初始开槽
  openTempering: ' &a装备打造已开槽.'
  # 开始淬炼
  startTempering: ' &a开始淬炼...'
  # 无法继续淬炼（装备已经顶级）
  cannotTempering: ' &a该装备已经不能再淬炼了.'
  # 空手时尝试淬炼
  emptyItem: ' &c您现在是空手!手持武器或装备再来吧! '
  # 无法淬炼的装备
  noType: ' &a该装备不是可淬炼的类型.'
  # 金币不足
  noMoney: ' &a淬炼到下一级需要{Money}金钱.'
  # 强化材料不足
  noMaterial: ' &c您已经没有足够的强化材料了!'
  # 淬炼成功
  success: ' &a恭喜你淬炼成功！'
  # 淬炼失败且掉级
  drop: ' &a很遗憾,淬炼失败,装备掉级.'
  # 淬炼失败但是没有掉级
  defeat: ' &a本次淬炼失败,装备不变.'

ItemName:
  DIAMOND_HELMET: '钻石头盔'
  DIAMOND_CHESTPLATE: '钻石胸甲'
  DIAMOND_LEGGINGS: '钻石护腿'
  DIAMOND_BOOTS: '钻石靴子'
  NETHERITE_HELMET: '下界合金头盔'
  NETHERITE_CHESTPLATE: '下界合金胸甲'
  NETHERITE_LEGGINGS: '下界合金护腿'
  NETHERITE_BOOTS: '下界合金靴'
  NETHERITE_AXE: '下界合金斧'
  NETHERITE_SWORD: '下界合金剑'
  IRON_AXE: '铁斧'
  DIAMOND_AXE: '钻石斧'
  DIAMOND_SWORD: '钻石剑'
  BOW: '弓箭'
  ELYTRA: '鞘翅'
  TRIDENT: '三叉戟'
  CROSSBOW: '弩箭'
  SHIELD: '盾牌'

bottomLores:
  - "材质"
  - "皮肤"

# 公告
BroadCast:
  # 是否启用
  enable: true
  # 公告内容
  messages:
    - "&a恭喜&e %player% &a将 %item% &a淬炼到了&c&l %level% &a级."
  # 当升级后的等级大于等于该等级，才发布公告
  allowLevel: 10


# 相关物品
Article:
  # 淬炼道具
  temperingTools:
    # 物品名
    displayName: "&b&l一级淬炼石"
    # 物品类型
    materialType: "DIAMOND"
    # 物品描述
    lores:
      - "&a这是一颗淬炼石"
      - "&a这真的是一颗淬炼石。"
    # 物品附魔效果，但是不会有任何属性显示。
    glow: true
    # 允许原版淬炼，无视上述的设定
    setNormal: true

  LuckyTools:
    displayName: "&b&l幸运石"
    # 物品类型
    materialType: "EMERALD"
    # 物品描述
    lores:
      - "&a这是一颗淬炼石"
      - "&a这真的是一颗淬炼石。"
    # 物品附魔效果，但是不会有任何属性显示。
    glow: true
    # 增加的成功概率
    luckValue: 30
    # 允许原版淬炼，无视上述的设定
    setNormal: true
Type:
  #武器
  Arms:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    # 包含的类型
    types:
      - IRON_SWORD
      - NETHERITE_AXE
      - NETHERITE_SWORD
      - IRON_AXE
      - DIAMOND_AXE
      - DIAMOND_SWORD
  #防具
  Armor:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    # 包含的类型
    types:
      - DIAMOND_HELMET
      - DIAMOND_CHESTPLATE
      - DIAMOND_LEGGINGS
      - DIAMOND_BOOTS
      - NETHERITE_HELMET
      - NETHERITE_CHESTPLATE
      - NETHERITE_LEGGINGS
      - NETHERITE_BOOTS
      - ELYTRA
      - SHIELD
  # 自定义
  wode:
    # 生效区
    # MainHand 主手
    # OffHand 副手
    # Armor 防具
    effectiveArea: "MainHand"
    types:
      - BOW
      - CROSSBOW
      - TRIDENT

  # 可以按照如上的自定义格式继续自定义


#等级部分
Level:
  0:
    lores:
      Arms:
        - '&7毛胚 I'
        - '&7⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o初次打造'
        - '&7&o已开槽'
      Armor:
        - '&7毛胚 I'
        - '&7⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o初次打造'
        - '&7&o已开槽'
      wode:
        - '&7毛胚 I'
        - '&7⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o初次打造'
        - '&7&o已开槽'
  1:
    # 升级到该等级的所需金钱
    money: 100
    # 升级到该等级需要的淬炼石个数
    materialAmount: 1
    # 升级到该等级的成功几率
    successRate: 90
    # 升级失败后的掉级几率
    # 掉级为掉到上一级
    # 若没有掉级，则无变化。
    downgradeRate: 50

    # 武器效果
    effect:
      Arms:
        # 伤害加成
        # 造成伤害时，在进行防御的减伤计算之前，对造成的伤害额外增加的值
        damageBonus: 100
      Armor:
        # 防御值
        # 受到伤害且攻击者为玩家时，最终结算好伤害后，额外减少伤害
        defense: 10
      wode:
        # 伤害加成
        # 造成伤害时，在进行防御的减伤计算之前，对造成的伤害额外增加的值
        damageBonus: 2.5
    # 当前等级的Lores
    lores:
      #武器方案
      Arms:
        - '&7普通 I'
        - '&7&o⬪⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o攻击力: +100 装备类型:主手'
      #装备方案
      Armor:
        - '&7普通 I'
        - '&7&o⬪⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o防御力: +0.2'
      wode:
        - '&7普通 I'
        - '&7&o⬪⬫⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o杀伤力: +2.5'
        - '&7&o槽位: 主手'
  2:
    # 升级到该等级的所需金钱
    money: 100
    # 升级到该等级需要的淬炼石个数
    materialAmount: 1
    # 升级到该等级的成功几率
    successRate: 90
    # 升级失败后的掉级几率
    # 掉级为掉到上一级
    # 若没有掉级，则无变化。
    downgradeRate: 50

    # 武器效果
    effect:
      Arms:
        # 伤害加成
        # 造成伤害时，在进行防御的减伤计算之前，对造成的伤害额外增加的值
        damageBonus: 200
      Armor:
        # 防御值
        # 受到伤害且攻击者为玩家时，最终结算好伤害后，额外减少伤害
        defense: 0.4
      wode:
        # 伤害加成
        # 造成伤害时，在进行防御的减伤计算之前，对造成的伤害额外增加的值
        damageBonus: 5
    # 当前等级的Lores
    lores:
      #武器方案
      Arms:
        - '&7普通 II'
        - '&7&o⬪⬪⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o攻击力: +200 装备类型:主手'
      #装备方案
      Armor:
        - '&7普通 II'
        - '&7&o⬪⬪⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o防御力: +0.4'
      wode:
        - '&7普通 II'
        - '&7&o⬪⬪⬫⬫⬫⬫⬫⬫⬫⬫'
        - '&7&o杀伤力: +5'
        - '&7&o槽位: 主手'