name: ReEquipment
version: '${project.version}'
main: org.reuac.reequipment.ReEquipment
api-version: '1.21'
depend: [ Vault ]
softdepend: [ CMI ]
commands:
  recl:
    description: "recl"
    permission: reequipment.main